import type {
  StressRegime,
  StressRegimeId,
} from "./warRoomTypes";

export const STRESS_REGIMES: StressRegime[] = [
  {
    id: "rates_shock",
    label: "Rates Shock",
    description: "Higher discount rates pressure long-duration growth while short-duration treasury exposure holds steadier.",
    defaultSeverity: "base",
    polarity: "downside",
    category: "Rates and policy",
    sectorShockPct: {
      ai_infrastructure: -11,
      cloud_computing: -9,
      semiconductors: -8,
      renewables: -7,
      utilities: -5,
      cash_treasuries: 1.2,
    },
    assetTypeShockPct: {
      stock: -4,
      etf: -2.5,
      treasury: 1,
      cash: 0,
    },
    betaShockMultiplier: -4.5,
    volatilityShockMultiplier: -0.08,
    liquidityHaircutPct: 1,
    warnings: ["Rates shock is a deterministic sensitivity, not a rates forecast."],
  },
  {
    id: "liquidity_crisis",
    label: "Liquidity Crisis",
    description: "A broad deleveraging tape penalizes beta, volatility, and less-liquid single-name exposure.",
    defaultSeverity: "severe",
    polarity: "downside",
    category: "Liquidity and leverage",
    sectorShockPct: {
      semiconductors: -12,
      ai_infrastructure: -13,
      cloud_computing: -10,
      cybersecurity: -9,
      biotech: -12,
      cash_treasuries: 2,
    },
    assetTypeShockPct: {
      stock: -10,
      etf: -6,
      treasury: 1.5,
      cash: 0,
    },
    betaShockMultiplier: -8,
    volatilityShockMultiplier: -0.2,
    liquidityHaircutPct: 5,
    warnings: ["Liquidity crisis assumes correlated selling across risky assets."],
  },
  {
    id: "ai_multiple_compression",
    label: "AI Multiple Compression",
    description: "AI infrastructure and adjacent growth themes re-rate lower while defensive assets absorb less damage.",
    defaultSeverity: "base",
    polarity: "downside",
    category: "AI valuation",
    sectorShockPct: {
      ai_infrastructure: -19,
      semiconductors: -17,
      cloud_computing: -12,
      cybersecurity: -9,
      broad_etfs: -4,
      cash_treasuries: 1,
    },
    assetTypeShockPct: {
      stock: -5,
      etf: -3,
      treasury: 0.8,
      cash: 0,
    },
    betaShockMultiplier: -5.5,
    volatilityShockMultiplier: -0.14,
    liquidityHaircutPct: 2,
    warnings: ["AI multiple compression is theme-specific and does not model company fundamentals."],
  },
  {
    id: "energy_spike",
    label: "Energy Spike",
    description: "Commodity inflation supports energy exposure while pressuring consumers, industrial margins, and rate-sensitive growth.",
    defaultSeverity: "base",
    polarity: "mixed",
    category: "Commodity shock",
    sectorShockPct: {
      energy: 10,
      oil_gas: 13,
      uranium: 5,
      nuclear_energy: 3,
      consumer: -6,
      industrials: -4,
      renewables: -5,
      broad_etfs: -2,
    },
    assetTypeShockPct: {
      stock: -1.5,
      etf: -0.5,
      treasury: 0.4,
      cash: 0,
    },
    betaShockMultiplier: -1.5,
    volatilityShockMultiplier: -0.05,
    liquidityHaircutPct: 1,
    warnings: ["Energy spike treats oil and gas as the positive shock channel."],
  },
  {
    id: "crypto_crash",
    label: "Crypto Crash",
    description: "A speculative-risk unwind hits high beta and growth even when the portfolio has no direct crypto holding.",
    defaultSeverity: "base",
    polarity: "downside",
    category: "Risk appetite",
    sectorShockPct: {
      ai_infrastructure: -8,
      semiconductors: -7,
      cloud_computing: -6,
      biotech: -7,
      cash_treasuries: 1,
    },
    assetTypeShockPct: {
      stock: -5,
      etf: -2.5,
      treasury: 0.8,
      cash: 0,
    },
    betaShockMultiplier: -6.5,
    volatilityShockMultiplier: -0.16,
    liquidityHaircutPct: 3,
    warnings: ["Crypto crash is modeled as a risk-appetite shock, not direct token exposure."],
  },
  {
    id: "recession",
    label: "Recession",
    description: "Cyclicals and high-beta assets weaken while healthcare, utilities, cash, and short treasuries defend capital.",
    defaultSeverity: "base",
    polarity: "downside",
    category: "Macro slowdown",
    sectorShockPct: {
      consumer: -8,
      industrials: -9,
      financials: -7,
      semiconductors: -8,
      healthcare: -1,
      utilities: 0.5,
      cash_treasuries: 2,
    },
    assetTypeShockPct: {
      stock: -6,
      etf: -4,
      treasury: 1.5,
      cash: 0,
    },
    betaShockMultiplier: -5,
    volatilityShockMultiplier: -0.12,
    liquidityHaircutPct: 2,
    warnings: ["Recession stress is broad and does not model policy response timing."],
  },
  {
    id: "melt_up",
    label: "Melt-Up",
    description: "A broad risk-on rally rewards growth, beta, and cyclicals while cash creates opportunity cost.",
    defaultSeverity: "base",
    polarity: "upside",
    category: "Risk-on upside",
    sectorShockPct: {
      ai_infrastructure: 13,
      semiconductors: 12,
      cloud_computing: 9,
      cybersecurity: 8,
      consumer: 5,
      industrials: 5,
      cash_treasuries: -0.5,
    },
    assetTypeShockPct: {
      stock: 6,
      etf: 4,
      treasury: -0.5,
      cash: 0,
    },
    betaShockMultiplier: 4.5,
    volatilityShockMultiplier: 0.06,
    liquidityHaircutPct: 0,
    warnings: ["Melt-up highlights opportunity cost; it is not an upside forecast."],
  },
  {
    id: "soft_landing",
    label: "Soft Landing",
    description: "Inflation cools without a demand break, supporting diversified equity beta and moderate growth exposure.",
    defaultSeverity: "base",
    polarity: "upside",
    category: "Macro upside",
    sectorShockPct: {
      broad_etfs: 5,
      semiconductors: 7,
      ai_infrastructure: 7,
      cloud_computing: 6,
      consumer: 5,
      industrials: 4,
      financials: 4,
      cash_treasuries: -0.4,
    },
    assetTypeShockPct: {
      stock: 3.5,
      etf: 3,
      treasury: 0.4,
      cash: 0,
    },
    betaShockMultiplier: 2.5,
    volatilityShockMultiplier: 0.03,
    liquidityHaircutPct: 0,
    warnings: ["Soft landing is modeled as an upside macro sensitivity, not a base-case forecast."],
  },
  {
    id: "fed_pivot",
    label: "Fed Pivot",
    description: "A friendlier policy path lowers discount-rate pressure and lifts growth, duration, and treasury-sensitive exposures.",
    defaultSeverity: "base",
    polarity: "upside",
    category: "Policy upside",
    sectorShockPct: {
      ai_infrastructure: 12,
      semiconductors: 11,
      cloud_computing: 10,
      cybersecurity: 7,
      renewables: 8,
      utilities: 3,
      broad_etfs: 5,
      cash_treasuries: 2,
    },
    assetTypeShockPct: {
      stock: 4,
      etf: 3,
      treasury: 2,
      cash: 0,
    },
    betaShockMultiplier: 3,
    volatilityShockMultiplier: 0.04,
    liquidityHaircutPct: 0,
    warnings: ["Fed pivot assumes policy relief without a simultaneous earnings shock."],
  },
  {
    id: "ai_capex_acceleration",
    label: "AI Capex Acceleration",
    description: "Hyperscaler and enterprise AI spending beats expectations, rewarding chips, cloud, power, and security rails.",
    defaultSeverity: "base",
    polarity: "upside",
    category: "AI upside",
    sectorShockPct: {
      ai_infrastructure: 17,
      semiconductors: 15,
      cloud_computing: 10,
      cybersecurity: 8,
      nuclear_energy: 6,
      energy: 4,
      broad_etfs: 4,
      cash_treasuries: -0.6,
    },
    assetTypeShockPct: {
      stock: 5,
      etf: 3,
      treasury: -0.3,
      cash: 0,
    },
    betaShockMultiplier: 3.8,
    volatilityShockMultiplier: 0.05,
    liquidityHaircutPct: 0,
    warnings: ["AI capex acceleration does not validate valuation or earnings-revision quality by itself."],
  },
  {
    id: "productivity_boom",
    label: "Productivity Boom",
    description: "AI and automation lift margins, capex efficiency, and real growth across industrial, cloud, and broad-market exposures.",
    defaultSeverity: "base",
    polarity: "upside",
    category: "Productivity upside",
    sectorShockPct: {
      ai_infrastructure: 10,
      cloud_computing: 9,
      semiconductors: 8,
      industrials: 8,
      financials: 5,
      consumer: 5,
      broad_etfs: 6,
      cash_treasuries: -0.5,
    },
    assetTypeShockPct: {
      stock: 5,
      etf: 4,
      treasury: -0.2,
      cash: 0,
    },
    betaShockMultiplier: 2.5,
    volatilityShockMultiplier: 0.03,
    liquidityHaircutPct: 0,
    warnings: ["Productivity boom is an upside regime and should be checked against valuation already embedded in prices."],
  },
  {
    id: "earnings_recession",
    label: "Earnings Recession",
    description: "Margins and forward estimates reset lower even without a full macro recession, pressuring cyclicals and high-multiple growth.",
    defaultSeverity: "base",
    polarity: "downside",
    category: "Earnings downside",
    sectorShockPct: {
      semiconductors: -10,
      ai_infrastructure: -9,
      cloud_computing: -8,
      consumer: -9,
      industrials: -10,
      financials: -8,
      healthcare: -2,
      cash_treasuries: 1.5,
    },
    assetTypeShockPct: {
      stock: -8,
      etf: -5,
      treasury: 1.2,
      cash: 0,
    },
    betaShockMultiplier: -5,
    volatilityShockMultiplier: -0.1,
    liquidityHaircutPct: 1.5,
    warnings: ["Earnings recession models estimate risk, not company-specific guidance cuts."],
  },
  {
    id: "stagflation",
    label: "Stagflation",
    description: "Sticky inflation and slowing demand pressure duration, margins, and consumers while commodity-linked exposure partly offsets.",
    defaultSeverity: "severe",
    polarity: "downside",
    category: "Inflation downside",
    sectorShockPct: {
      energy: 7,
      oil_gas: 9,
      uranium: 4,
      ai_infrastructure: -11,
      semiconductors: -10,
      cloud_computing: -9,
      consumer: -10,
      industrials: -8,
      renewables: -7,
      utilities: -2,
      cash_treasuries: 0.5,
    },
    assetTypeShockPct: {
      stock: -5,
      etf: -3,
      treasury: -2,
      cash: 0,
    },
    betaShockMultiplier: -4,
    volatilityShockMultiplier: -0.13,
    liquidityHaircutPct: 2,
    warnings: ["Stagflation assumes inflation shock and weak demand arrive together."],
  },
  {
    id: "dollar_spike",
    label: "Dollar Spike",
    description: "A sharp USD rally tightens global financial conditions and pressures commodities, multinationals, and risk appetite.",
    defaultSeverity: "base",
    polarity: "downside",
    category: "Global liquidity",
    sectorShockPct: {
      semiconductors: -7,
      ai_infrastructure: -6,
      cloud_computing: -5,
      energy: -5,
      oil_gas: -6,
      renewables: -5,
      financials: -3,
      cash_treasuries: 1.2,
    },
    assetTypeShockPct: {
      stock: -4,
      etf: -2.5,
      treasury: 1,
      cash: 0,
    },
    betaShockMultiplier: -3.5,
    volatilityShockMultiplier: -0.07,
    liquidityHaircutPct: 1,
    warnings: ["Dollar spike is a global-liquidity proxy and does not model FX revenue translation by issuer."],
  },
  {
    id: "geopolitical_supply_shock",
    label: "Geopolitical Supply Shock",
    description: "Supply-chain disruption hits semiconductors and global cyclicals while defense, energy, and cash-like assets cushion.",
    defaultSeverity: "severe",
    polarity: "mixed",
    category: "Geopolitical shock",
    sectorShockPct: {
      semiconductors: -15,
      ai_infrastructure: -11,
      cloud_computing: -7,
      industrials: -6,
      defense: 9,
      aerospace: 6,
      energy: 8,
      oil_gas: 9,
      cash_treasuries: 1.5,
    },
    assetTypeShockPct: {
      stock: -5,
      etf: -3,
      treasury: 1,
      cash: 0,
    },
    betaShockMultiplier: -3.5,
    volatilityShockMultiplier: -0.12,
    liquidityHaircutPct: 2,
    warnings: ["Geopolitical supply shock is a top-down sensitivity and does not model issuer geography or revenue mix."],
  },
];

export function getStressRegime(id: StressRegimeId): StressRegime {
  const regime = STRESS_REGIMES.find((item) => item.id === id);
  if (!regime) throw new Error(`Unknown stress regime: ${id}`);
  return regime;
}

export function groupStressRegimesByPolarity(regimes: StressRegime[] = STRESS_REGIMES) {
  return {
    upside: regimes.filter((regime) => regime.polarity === "upside"),
    downside: regimes.filter((regime) => regime.polarity === "downside"),
    mixed: regimes.filter((regime) => regime.polarity === "mixed"),
  };
}
