<#
.SYNOPSIS
  Generate the AWS production deployment receipt (TASK-0903).

.DESCRIPTION
  Implements docs/AWS_DEPLOY_RUNBOOK.md §3.11 — the binding proof-of-deploy
  artifact. Combines:
    - `terraform output -json` snapshot (identifiers only, no secrets)
    - the most recent `aws-preflight-*.json` receipt
    - the most recent `aws-verify-*.json` receipt
    - operator sign-off metadata (name, date, git SHA)

  Output: a single Markdown receipt at
    reports/verification/aws-production-deployment-<YYYY-MM-DD>.md
  plus a sibling .json with the same metadata. These files are NOT
  gitignored — they are the audit trail.

  Per runbook §3.11, the receipt MUST contain:
    - Terraform plan output summary
    - Each verify section marked PASS/FAIL with the AWS CLI output pasted in
    - Output of `terraform output -json` (identifiers only, not secrets)
    - Sign-off line: "Operator: ____ Date: ____"

.PARAMETER OutputsFile
  Path to outputs.json (default infra/aws/outputs.json).

.PARAMETER PreflightReceipt
  Path to a specific preflight receipt JSON. Defaults to the most recent
  one in reports/verification/aws-preflight-*.json.

.PARAMETER VerifyReceipt
  Path to a specific verify receipt JSON. Defaults to the most recent
  one in reports/verification/aws-verify-*.json.

.PARAMETER OperatorName
  Operator sign-off name (written into the receipt's sign-off line).

.PARAMETER OperatorDate
  Operator sign-off date (default: today, YYYY-MM-DD).

.PARAMETER GitSha
  Git SHA to record on the receipt. Defaults to `git rev-parse HEAD`.

.PARAMETER OutDir
  Override the receipt output directory.

.PARAMETER DryRun
  Emit a "PENDING" receipt — no outputs/preflight/verify available yet.
  Used at TASK-0903 task completion time to mark the framework ready
  before any apply has run.

.EXAMPLE
  pwsh ./scripts/aws_receipt.ps1 -DryRun -OperatorName "Builder 1"

.EXAMPLE
  pwsh ./scripts/aws_receipt.ps1 -OperatorName "Builder 1" -OperatorDate 2026-06-25
#>

[CmdletBinding()]
param(
    [string]$OutputsFile = "",
    [string]$PreflightReceipt = "",
    [string]$VerifyReceipt = "",
    [string]$OperatorName = "",
    [string]$OperatorDate = "",
    [string]$GitSha = "",
    [string]$OutDir = "",
    [switch]$DryRun
)

Set-StrictMode -Version Latest
$ErrorActionPreference = "Continue"

$RepoRoot = Split-Path -Parent $PSScriptRoot
Set-Location $RepoRoot

if ([string]::IsNullOrEmpty($OutDir)) {
    $OutDir = Join-Path $RepoRoot "reports" "verification"
}
if (-not (Test-Path $OutDir)) {
    New-Item -ItemType Directory -Path $OutDir -Force | Out-Null
}
if ([string]::IsNullOrEmpty($OutputsFile)) {
    $OutputsFile = Join-Path $RepoRoot "infra" "aws" "outputs.json"
}
if ([string]::IsNullOrEmpty($OperatorDate)) {
    $OperatorDate = (Get-Date).ToString("yyyy-MM-dd")
}
if ([string]::IsNullOrEmpty($GitSha)) {
    try {
        $GitSha = (& git rev-parse HEAD 2>$null).Trim()
    } catch {
        $GitSha = "unknown"
    }
}

# Resolve the most recent preflight + verify receipts if not specified.
function Get-LatestReceipt {
    param([string]$Pattern)
    $matches = Get-ChildItem -Path $OutDir -Filter $Pattern -ErrorAction SilentlyContinue | Sort-Object LastWriteTime -Descending
    if ($matches.Count -gt 0) { return $matches[0].FullName }
    return $null
}
if (-not $DryRun -and [string]::IsNullOrEmpty($PreflightReceipt)) {
    $PreflightReceipt = Get-LatestReceipt "aws-preflight-*.json"
}
if (-not $DryRun -and [string]::IsNullOrEmpty($VerifyReceipt)) {
    $VerifyReceipt = Get-LatestReceipt "aws-verify-*.json"
}

$Date = $OperatorDate
$MdPath = Join-Path $OutDir "aws-production-deployment-$Date.md"
$JsonPath = Join-Path $OutDir "aws-production-deployment-$Date.json"

$Outputs = $null
if (Test-Path $OutputsFile) {
    try { $Outputs = Get-Content -Raw $OutputsFile | ConvertFrom-Json } catch { $Outputs = $null }
}

$Preflight = $null
if ($PreflightReceipt -and (Test-Path $PreflightReceipt)) {
    try { $Preflight = Get-Content -Raw $PreflightReceipt | ConvertFrom-Json } catch { $Preflight = $null }
}

$Verify = $null
if ($VerifyReceipt -and (Test-Path $VerifyReceipt)) {
    try { $Verify = Get-Content -Raw $VerifyReceipt | ConvertFrom-Json } catch { $Verify = $null }
}

$Status = if ($DryRun) { "PENDING" } elseif ($null -eq $Outputs) { "NO_OUTPUTS" } elseif ($null -ne $Verify -and $Verify.overall -eq "PASS") { "VERIFIED" } elseif ($null -ne $Verify) { "FAILED" } else { "UNVERIFIED" }

$md = New-Object System.Text.StringBuilder
[void]$md.AppendLine("# AWS Production Deployment Receipt — $Date")
[void]$md.AppendLine("")
[void]$md.AppendLine("> Generated by ``scripts/aws_receipt.ps1`` (TASK-0903).")
[void]$md.AppendLine("> This receipt implements docs/AWS_DEPLOY_RUNBOOK.md §3.11.")
[void]$md.AppendLine("> It is the binding proof-of-deploy artifact for the Fincept AWS production control plane.")
[void]$md.AppendLine("")
[void]$md.AppendLine("**Receipt status:** $Status")
[void]$md.AppendLine("")
[void]$md.AppendLine("| Field | Value |")
[void]$md.AppendLine("|---|---|")
[void]$md.AppendLine("| Date | $OperatorDate |")
[void]$md.AppendLine("| Git SHA | $GitSha |")
[void]$md.AppendLine("| Operator | $(if ([string]::IsNullOrEmpty($OperatorName)) { '<to be filled in by operator>' } else { $OperatorName }) |")
[void]$md.AppendLine("| Outputs file | $(if ($null -ne $Outputs) { $OutputsFile } else { '(not present)' }) |")
[void]$md.AppendLine("| Preflight receipt | $(if ($null -ne $Preflight) { $PreflightReceipt } else { '(not present)' }) |")
[void]$md.AppendLine("| Verify receipt | $(if ($null -ne $Verify) { $VerifyReceipt } else { '(not present)' }) |")
[void]$md.AppendLine("")

[void]$md.AppendLine("## Pre-flight")
[void]$md.AppendLine("")
if ($null -ne $Preflight) {
    [void]$md.AppendLine("- **Overall:** $($Preflight.overall)")
    [void]$md.AppendLine("- **Pass / Fail / Skipped:** $($Preflight.summary.pass) / $($Preflight.summary.fail) / $($Preflight.summary.skipped)")
    [void]$md.AppendLine("- **Required failures:** $($Preflight.summary.required_failures)")
    [void]$md.AppendLine("- **Started:** $($Preflight.started_at)")
    [void]$md.AppendLine("- **Duration:** $($Preflight.duration_s)s")
    if ($Preflight.summary.required_failures -gt 0) {
        [void]$md.AppendLine("")
        [void]$md.AppendLine("Failed checks:")
        foreach ($c in $Preflight.checks) {
            if ($c.status -eq "fail") {
                [void]$md.AppendLine("- $($c.name): $($c.detail)"
                )
            }
        }
    }
} else {
    [void]$md.AppendLine("_No preflight receipt available. Run ``scripts/aws_preflight.ps1`` first._")
}
[void]$md.AppendLine("")

[void]$md.AppendLine("## Terraform outputs (identifiers only)")
[void]$md.AppendLine("")
if ($null -ne $Outputs) {
    # outputs.tf scrubs all secret values already. We list every output
    # value alongside its description for the audit trail.
    foreach ($prop in $Outputs.PSObject.Properties) {
        $val = $prop.Value.value
        $sensitive = $prop.Value.sensitive
        $display = if ($sensitive) { "<scrubbed — sensitive>" } else { if ($null -ne $val) { ($val | ConvertTo-Json -Compress -Depth 4) } else { "(null)" } }
        [void]$md.AppendLine("- **$($prop.Name):** $display")
    }
} else {
    [void]$md.AppendLine("_No outputs.json available. Run ``terraform output -json > outputs.json`` (runbook §2.5) and re-run this script._")
}
[void]$md.AppendLine("")

[void]$md.AppendLine("## Post-apply verification (§3.1–§3.10)")
[void]$md.AppendLine("")
if ($null -ne $Verify) {
    [void]$md.AppendLine("- **Overall:** $($Verify.overall)")
    [void]$md.AppendLine("- **Pass / Fail / Skipped:** $($Verify.summary.pass) / $($Verify.summary.fail) / $($Verify.summary.skipped)")
    [void]$md.AppendLine("- **Required failures:** $($Verify.summary.required_failures)")
    [void]$md.AppendLine("")
    [void]$md.AppendLine("### Per-section detail")
    [void]$md.AppendLine("")
    $bySection = $Verify.checks | Group-Object -Property section
    foreach ($grp in $bySection) {
        [void]$md.AppendLine("**§$($grp.Name)** — $($grp.Count) check(s):")
        foreach ($c in $grp.Group) {
            $line = "- $($c.name): **$($c.status)** (exit $($c.exit_code), $($c.duration_ms)ms)"
            if ($c.status -eq "fail") {
                $line += "  `n  > $($c.detail)"
            }
            [void]$md.AppendLine($line)
        }
        [void]$md.AppendLine("")
    }
    if ($Verify.summary.required_failures -gt 0) {
        [void]$md.AppendLine("**Deployment FAILS verification.** Do not mark complete. Fix the failed checks above and re-run ``scripts/aws_postapply_verify.ps1``.")
        [void]$md.AppendLine("")
    }
} else {
    [void]$md.AppendLine("_No verify receipt available. Run ``scripts/aws_postapply_verify.ps1`` after ``terraform apply``._")
}
[void]$md.AppendLine("")

[void]$md.AppendLine("## Known follow-ups (from runbook §6)")
[void]$md.AppendLine("")
[void]$md.AppendLine("- [ ] Auto-scaling policies on the API service (target-tracking on CPU + memory).")
[void]$md.AppendLine("- [ ] RDS Proxy for connection pooling.")
[void]$md.AppendLine("- [ ] Secrets Manager rotation Lambda for the DB password.")
[void]$md.AppendLine("- [ ] CodePipeline for image CI/CD (currently operator-driven via `docker push`).")
[void]$md.AppendLine("- [ ] Cost anomaly detection alarms.")
[void]$md.AppendLine("- [ ] Disaster recovery (cross-region snapshot copy for RDS, S3 CRR for audit buckets).")
[void]$md.AppendLine("")

[void]$md.AppendLine("## Sign-off")
[void]$md.AppendLine("")
[void]$md.AppendLine("- Operator: $(if ([string]::IsNullOrEmpty($OperatorName)) { '____________________' } else { $OperatorName })")
[void]$md.AppendLine("- Date: $OperatorDate")
[void]$md.AppendLine("- Git SHA: $GitSha")
[void]$md.AppendLine("- Receipt status: **$Status**")
[void]$md.AppendLine("")

[System.IO.File]::WriteAllText($MdPath, $md.ToString())

$json = [ordered]@{
    schema = "fincept.aws-deployment-receipt/v1"
    status = $Status
    operator = $OperatorName
    date = $OperatorDate
    git_sha = $GitSha
    sources = [ordered]@{
        outputs_file = if (Test-Path $OutputsFile) { $OutputsFile } else { $null }
        preflight_receipt = $PreflightReceipt
        verify_receipt = $VerifyReceipt
    }
    preflight = if ($null -ne $Preflight) { $Preflight.summary } else { $null }
    verify = if ($null -ne $Verify) { $Verify.summary } else { $null }
    outputs = if ($null -ne $Outputs) { $Outputs } else { $null }
}
$json | ConvertTo-Json -Depth 8 | Out-File -FilePath $JsonPath -Encoding utf8

Write-Host ""
Write-Host "Receipt written:" -ForegroundColor Green
Write-Host "  $MdPath" -ForegroundColor DarkGray
Write-Host "  $JsonPath" -ForegroundColor DarkGray
Write-Host "Status: $Status" -ForegroundColor $(if ($Status -eq "VERIFIED") { "Green" } elseif ($Status -eq "PENDING") { "Yellow" } else { "Red" })

exit 0